# Ordinal Encoding

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
df = pd.read_csv('customer.csv')
df.sample(5)

age  gender   review education purchased
9    74    Male     Good        UG       Yes
14   15    Male     Poor        PG       Yes
4    16  Female  Average        UG        No
42   30  Female     Good        PG       Yes
0    30  Female  Average    School        No

In [12]:
df = df.iloc[:,2:]

In [16]:
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [20]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:,:2], df['purchased'], test_size = 0.2)

In [28]:
# x_train

In [30]:
# y_train

In [42]:
from sklearn.preprocessing import OrdinalEncoder

In [50]:
oe = OrdinalEncoder(categories = [['Poor', 'Average', 'Good'],['School', 'UG', 'PG']])

In [52]:
oe

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [58]:
oe.fit(x_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [60]:
x_train = oe.transform(x_train)
x_test = oe.transform(x_test)

In [62]:
x_train

array([[0., 0.],
       [2., 2.],
       [0., 1.],
       [0., 2.],
       [2., 2.],
       [2., 0.],
       [1., 2.],
       [1., 1.],
       [0., 1.],
       [1., 2.],
       [0., 2.],
       [2., 1.],
       [0., 1.],
       [0., 1.],
       [2., 0.],
       [1., 2.],
       [1., 0.],
       [0., 0.],
       [0., 2.],
       [2., 1.],
       [2., 2.],
       [2., 0.],
       [2., 0.],
       [0., 2.],
       [2., 2.],
       [0., 0.],
       [0., 2.],
       [1., 0.],
       [0., 2.],
       [1., 0.],
       [2., 1.],
       [0., 0.],
       [0., 2.],
       [2., 1.],
       [1., 1.],
       [1., 1.],
       [2., 2.],
       [0., 2.],
       [1., 1.],
       [1., 1.]])

In [64]:
x_test

array([[1., 0.],
       [2., 1.],
       [0., 0.],
       [2., 2.],
       [0., 2.],
       [2., 0.],
       [2., 1.],
       [2., 0.],
       [1., 0.],
       [1., 1.]])

In [66]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

# Label Encoding

In [73]:
df = pd.read_csv('customer.csv')
df.sample(5)

age  gender review education purchased
11   74    Male   Good        UG       Yes
26   53  Female   Poor        PG        No
14   15    Male   Poor        PG       Yes
25   57  Female   Good    School        No
36   34  Female   Good        UG       Yes

In [77]:
# df.iloc[:,4]

In [89]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:,-1],
                                                     df['purchased'],
                                                     test_size = 0.2,
                                                     random_state = 0)
                   

In [91]:
x_train

33    Yes
35    Yes
26     No
34     No
18     No
7     Yes
14    Yes
45    Yes
48    Yes
29    Yes
15     No
30     No
32    Yes
16    Yes
42    Yes
20    Yes
43     No
8      No
13     No
25     No
5     Yes
17    Yes
40     No
49     No
1      No
12     No
37    Yes
24    Yes
6      No
23     No
36    Yes
21     No
19    Yes
9     Yes
39     No
46     No
3      No
0      No
47    Yes
44     No
Name: purchased, dtype: object

In [99]:
x_test

28     No
11    Yes
10    Yes
41    Yes
2      No
27     No
38     No
31    Yes
22    Yes
4      No
Name: purchased, dtype: object

In [79]:
from sklearn.preprocessing import LabelEncoder

In [101]:
le = LabelEncoder()

In [103]:
le.fit(y_train)

LabelEncoder()

In [105]:
x_train = le.transform(x_train)
x_test = le.transform(x_test)

In [107]:
x_train

array([1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0])

In [111]:
x_test

array([0, 1, 1, 1, 0, 0, 0, 1, 1, 0])